14:04:00 UploadAttachment_ContentId:JOmoEmfLweUoK48Tp04F:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:03 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:03 Create content: SwiftProcessSWI20190517135834 error
14:04:08 UploadAttachment_ContentId:DEeo5pyowPXDbZPaRdJN:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:10 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:10 Create content: Send2Br_BGProcessMBS20190517135847 error
14:04:11 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:11 Create content: RefinanceProcessUTN20190517135840 error
14:04:24 UploadAttachment_ContentId:tzIbukMRHEzN84TmyZEe:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:25 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:25 Create content: Send2Br_ExpProcessMEA20190517135857 error
14:04:37 UploadAttachment_ContentId:BvHA7muAk0V7cGuonu5P:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:38 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:38 Create content: InternalProcessXKC20190517135931 error
14:04:55 UploadAttachment_ContentId:0YFIeGXJRU6UqJe5T6kb:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:57 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:04:57 Create content: BGProcess36I20190517135957 error
14:05:10 UploadAttachment_ContentId:NnQJuisblYUDYW4jnVZ3:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:05:11 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:05:11 Create content: ExportProcessLCO20190517140039 error
14:05:16 UploadAttachment_ContentId:FQNtMCJJsGiYcR5WRUBa:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:05:18 Profile_{"Message":"Object reference not set to an instance of an object.","StackTrace":"   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.Services.WorkflowItemService.Insert(WorkflowItem wfItem, Boolean autoProcess) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\WorkflowItemService.cs:line 73\r\n   at UCMS.WebAPI.Controllers.WorkflowItemController.<>c__DisplayClass1_0.<Insert>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\WorkflowItemController.cs:line 26\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
14:05:18 Create content: ImportProcess16X20190517140051 error
